### ISSUE TITLE
Hover over to see time

### ISSUE THREAD

**Issue by jonese1234** [jamesrom/jamesrom.github.io#1]
It would be a nice idea so when you hover over the column it will have the time that it reached.

as when you leave it running for a while it is quite hard to tell at what time it reset.

**Comment by FoxxMD** [comment]
:+1:

**Comment by NotBlizzard** [comment]
Great idea.

**Comment by Drewsapple111** [comment]
This would be a great feature, +1.
I might try to add it myself.

**Comment by jamesrom** [comment]
I've had a crack at this. It's fairly basic at the moment, but I'm happy with the results.
