### ISSUE TITLE
Error 500 from redditmedia

### ISSUE THREAD

**Issue by vinvin27** [jamesrom/jamesrom.github.io#13]
Hey,

The monitoring doesn't works, I got an error 500 : 
WebSocket connection to 'wss://wss.redditmedia.com/thebutton?h=0ac3a25d899813fdf6ce06b0e80b7ef56a850bce&e=1428493002' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by flyingrub** [comment]
You should try to get it updated automaticaly

**Comment by vinvin27** [comment]
Ok but where I can find it ?

**Comment by bcspragu** [comment]
You can automatically update the `h` and `e` handshake values by using ajax to load the page, and then parsing it out of the script tag in the head, the `#config` one.

**Comment by bityon** [comment]
@vinvin27  doesn't work indeed, same error

**Comment by lezed1** [comment]
I just submitted a fix for this in #15!
