### ISSUE TITLE
Introduce timeouts or CSS animations to reduce CPU usage

### ISSUE THREAD

**Issue by adomasven** [jamesrom/jamesrom.github.io#16]
Hi. I couldn't quite track down the piece of code that needs changing, do not have loads of time, but in general, I noticed that when I have the tab open, it is running at around 70% CPU usage. This indicates busy waiting (redrawing with a while loop somewhere?).

It is probably a good idea to leverage [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout) and redraw, say, 60 or 120 times a second (the refresh rate of standard monitors). An alternative could be using CSS transitions, but that might be hard to get right such that it looks smoothly.

Heavy CPU usage isn't a huge problem per se, but I work on dual-screen, sometimes doing CPU intensive work, which makes having the page open slow my computer down a bit. And if you are running on a battery, having the CPU usage so high drains it quite heavily.

**Comment by FoxxMD** [comment]
:+1: I experience the same thing. My macbook starts getting crazy hot and cpu usage stays high when I have the monitor open. I also work with dual monitors and am doing webdev and can't afford to have the monitor open while compiling because it's such a CPU hog.

**Comment by jamesrom** [comment]
Currently it uses [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) for animation, instead of setTimeout. It should not draw more than 60fps.

If anyone wants to look into it, check out [timer.js line 36](https://github.com/jamesrom/jamesrom.github.io/blob/master/timer.js#L36)

**Comment by jamesrom** [comment]
Can someone confirm that CPU usage has improved?

See #26

**Comment by FoxxMD** [comment]
:+1: huge improvement for me. Thanks!

**Comment by lezed1** [comment]
I have a few tabs of the tacker open, and I'm <10% CPU on my laptop. I'd say this has been completely resolved!
