### ISSUE TITLE
Recent change causes unsafe content errors when visiting using https

### ISSUE THREAD

**Issue by r04r** [jamesrom/jamesrom.github.io#21]
3e6d586a57815668478db57e6dcfbd53790b4ca1 changed // to http:// which causes unsafe content warnings when https://jamesrom.github.io/ is loaded over https. The loading over https happens automatically for users of https anywhere.

**Comment by r04r** [comment]
If you want to develop locally just run a web server. I like the [xampp](https://www.apachefriends.org/index.html) bundle.

**Comment by MiestrSpounk** [comment]
I agree, it was fine before. If you want to develop locally, you don't even need tu use a web server, just add the "http:" manually, it takes 10 seconds...

**Comment by jamesrom** [comment]
Ok I will revert changes.

I personally use the node module http-server for a basic file web server.
