### ISSUE TITLE
Describe some of the terms in the README

### ISSUE THREAD

**Issue by jarrodconnolly** [jamesrom/jamesrom.github.io#25]
This project keeps getting better.

I would love to see a better explanation of what all the terms mean, especially the new ones on the hover popup.

What does "Clicks" mean and how can there be more than one person clicking at a specific bar? I thought only one person could get a specific number and then it reset.

Also explain what "Resets" means and how it relates to clicks.

Thank you.

**Comment by jamesrom** [comment]
Readme updated. Thanks.
