### ISSUE TITLE
Click info popup extend past the normal page boundrys

### ISSUE THREAD

**Issue by lezed1** [jamesrom/jamesrom.github.io#28]
Currently a info popup on the far left or far right can be too wide and increase the width of the page. Here is an example on the right side overextending:

![image](https://cloud.githubusercontent.com/assets/2121068/7103281/c556a15e-e06d-11e4-8e9c-71cd6ae3ecf7.png)

The page can be scrolled rightward to see the full popup, but far left popups are just cutoff. A workaround for users is to zoom in so that the center of the click bar is farther from the edge of the page.

**Comment by jamesrom** [comment]
I really am tempted to roll my own popup. Currently it's powered by [d3-tip](https://github.com/Caged/d3-tip) with custom styling, and some limitations (such as this issue) make it a bit fiddly.

A workaround fix has been merged. See 0b26968081e1a4364cdd9df9fb52c2ed5bf9b7a2.

**Comment by lezed1** [comment]
This does work, but part of the popup is just not visible. d3-tip seems to be a popular library, but I couldn't find an option/workaround/fix to not allow the tooltip to extend past the graph. Rolling your own, or modifying d3-tip seems like the best choice, but it also sounds like a fair bit of work.

**Comment by lezed1** [comment]
Actually, maybe this could work: https://github.com/Caged/d3-tip/blob/master/docs/positioning-tooltips.md#tipoffset

Maybe the offset could range from -width/2 to width/2?
