### ISSUE TITLE
Empty columns?

### ISSUE THREAD

**Issue by CaBz** [jamesrom/jamesrom.github.io#30]
Hello,

It seems that there are a few empty columns. See from the screenshot: http://i.imgur.com/qVJ4wY5.png

From the left it's your application, from the right it's mine. I'm comparing both and it seems that you have a few empty spots. It seems very random.

**Comment by jamesrom** [comment]
That's likely people clicking at 60s.

**Comment by CaBz** [comment]
Makes sense. I must have a bug of my own then. Thanks!
