### ISSUE TITLE
Trendline

### ISSUE THREAD

**Issue by freaktechnik** [jamesrom/jamesrom.github.io#32]
I think a trendline would be pretty nice (and easy enough to achieve with d3), especially since the actual lines start to be too thin if the site has run for too long.

**Comment by jamesrom** [comment]
I am currently working on a [Simple Moving Average](http://en.wikipedia.org/wiki/Moving_average#Simple_moving_average).

Happy to accept PRs for a trendline, though.

**Comment by voidref** [comment]
Has adding a median been considered? I took a look at the code, but I am not familiar enough with javascript to know what exactly is going on with the data.

The algo is basically:

    sort all click times
    grab the value at the middle index of the sorted list

aka

    median = sortedTimesList[sortedTimesList.count / 2]

**Comment by voidref** [comment]
Submitted a PR, I guess I'm also a javascript programmer now!

**Comment by jamesrom** [comment]
Thanks for contributing, I'm cleaning up this repo now (3 years later!)

**Comment by jamesrom** [comment]
Thanks for contributing, I'm cleaning up this repo now (3 years later!)
