### ISSUE TITLE
Enable a "sorted mode" which sorts clicks in decreasing order

### ISSUE THREAD

**Issue by kqr** [jamesrom/jamesrom.github.io#34]
The reason for this is that the highest bar (least time remaining on timer) would be closest to the current bar, which would give you a sense of how "good" the current run is compared to the slope to the left of it.

This feels like something quick (button which toggles a boolean which controls whether or not to sort the data points) but I'm not familiar enough with the technologies involved to whip it together, unfortunately.

**Comment by lezed1** [comment]
I'm not exactly sure what you are requesting. Are you asking for an option that takes each bar are rearranges them not by time stamp, but by height and have the current bar (that is growing) being live placed in the correct position, moving to a higher and higher position?

**Comment by kqr** [comment]
I was actually thinking having the current bar at the very right, like it is right now. That way, it's easy to compare the current bar to the tallest bar because they're right next to each other. (And you can also sort of visual inspect how the current bar is doing compared to the general trend of the other bars. With the current time sort, you have to wait for a really long time before a trend appears.)

**Comment by lezed1** [comment]
I personally don't see the usefulness for this feature, but I will look at it again after some other things (such as reconnecting). If you submit a Pull Request I will definitely look at it, and I think I will like the feature more if I saw it.

You mentioned you aren't familiar with the technologies used, so  I'm assuming that is mostly D3. If you can hack something together great, if not I'll come back to this later!

**Comment by kqr** [comment]
Hah, yeah, it's not really a Big Important Feature, just something I thought'd be nice. If I find time this weekend I might take a closer look. We'll see!

**Comment by jarlefosen** [comment]
@kqr Check out http://jarlefosen.github.io/thebutton_monitor/
Is that what you were looking for?
Note the checkbox in the upper left corner.

**Comment by lezed1** [comment]
@jarlefosen, I believe this is (at at least very similar) to what @kqr was looking for. I believe that this feature should not be added.

I don't think there is enough visual marking denoting what is actually going on in the sorted mode - it just looks like a lot of people worked together to get a pattern. To me, it just doesn't fit in with this tracker.

I do however like the general idea and you should definitely check out this tracker: http://treyp.github.io/thebutton/ - you may find the "Distribution" tab interesting. I am a huge fan of that tracker, and I think it fits perfectly there. This one is meant to be really simple and everything be perfectly obvious at first glance.

I also found one minor bug because I decided to process disconnects in a certain way. I have a disconnect appear as a -.01 second push that renders white to appear as if the graph was broken. This super low press gets sorted all the way to the left. I'm not sure where it should actually go, or even if it should be shown at all.

So personally I don't think this should be merged in, but if you do please say so. I like the idea, but not as it is right now. If we can come up with a better way then I am happy to help implement it, test it and merge it!

**Comment by lezed1** [comment]
I also got a nice graph by leaving it running for a while. Here is a screenshot:

![Screenshot](http://i.imgur.com/Vbe22XT.png)

After seeing this with a large data set, I prefer the others tracker's way of denoting the different number of clicks at each time. This uses width to represent click, while the other one uses height. I believe height makes more sense. I also don't see a reason to copy that idea when it already works perfectly over there.

**Comment by kqr** [comment]
@jarlefosen Precisely that... except in ascending order, such that the tallest bars are to the right. That makes it easier to compare the current count to the tallest bar so far. (As a bonus, that'd mean the information display does not cover up any part of the graph.)

**Comment by kqr** [comment]
@lezed1 The distribution tab on the other counter you linked is neat, but a bit too messy for my tastes. I do prefer the simplicity of having width to represent clicks.

**Comment by lezed1** [comment]
The display has actually grown on me a bit (and I agree it looks backwards). If the direction is reversed, I doubt you could easily see the bar height of the current bar after some time (like in the picture I linked below, each bar is tiny).

![Screenshot](http://i.imgur.com/ankrJVf.png)

I've independently considered adding a horizontal line that allows you to compare the current time to the historical graph. I think that these two options (sorted mode and horizontal line) are good features to add in, but I think their options should be placed into a settings panel. I will work on the panel when I get a chance (I think James started a branch) and put these toggles in there.

**Comment by kqr** [comment]
@lezed1 Each bar is tiny, but you could zoom in to see just the tallest bars next to the current bar.

**Comment by lezed1** [comment]
But you can't see that bar and the whole distribution graph. I horizontal line would allow you to compare the current time to the entire history you have recorded.

**Comment by jarlefosen** [comment]
I reversed the sorting, what do you think?
It's definitely easier to compare this way. But a horizontal line would probably be even better.

![reversed_sorting](https://cloud.githubusercontent.com/assets/2993240/7556229/af24243a-f768-11e4-9758-2f78591714ac.png)

**Comment by lezed1** [comment]
You may want to remove disconnect-representing bars (clicks at less than 0 seconds) when sorting. Try testing it when you lose internet in the middle.

**Comment by jarlefosen** [comment]
Thanks, didn't know about less-than-zero events. They are now hidden in sorted-mode.

I could send a pull request if you want, but I don't think it's needed before the settings panel is implemented.

**Comment by kqr** [comment]
Ah, yeah, a horizontal line would be even better. I had missed that suggestion. The reversed sorting looks awesome!

**Comment by jamesrom** [comment]
Thanks for contributing, I'm cleaning up this repo now (3 years later!)
