### ISSUE TITLE
Individual bars pop in and out of visibility once number of resets outnumber the pixel width of the graph

### ISSUE THREAD

**Issue by roothorick** [jamesrom/jamesrom.github.io#8]
In other words, you're not gracefully handling the case of not having enough horizontal pixels to show every reset. So, resets falling on just the wrong subpixel positions aren't shown at all until they move.

For me, it only took leaving it open for about two hours for this to start happening

Scrollbar seems like the easy answer.

**Comment by jamesrom** [comment]
Thanks to @MiestrSpounk we now have zooming and panning. See #10.
