### ISSUE TITLE
Incorrectly flaired columns.

### ISSUE THREAD

**Issue by ZaneDubya** [jamesrom/jamesrom.github.io#9]
I noticed that some of the bars appear to be incorrectly flaired: 
![screen shot 2015-04-06 at 10 22 01 am](https://cloud.githubusercontent.com/assets/7041719/7006455/e647492a-dc46-11e4-8573-2bb8a8a87253.png)
My stats at the time:
![screen shot 2015-04-06 at 10 22 14 am](https://cloud.githubusercontent.com/assets/7041719/7006458/e85ba026-dc46-11e4-8975-e0d873878df1.png)

**Comment by ZaneDubya** [comment]
... unless, of course, this bar is 51s long.

**Comment by captbaritone** [comment]
Seeing this too.

**Comment by jamesrom** [comment]
That looks right to me. The bar is 51 seconds long by the look of it. I'm going to add the ability to hover over bars to view info about them, so I can confirm then.

**Comment by GLundh** [comment]
Bars 51 is colored blue here:

![image](https://cloud.githubusercontent.com/assets/300900/7074689/ad7a5b24-defc-11e4-997d-735b6133b39d.png)

But the official wiki states that blue is 41-50:

![image](https://cloud.githubusercontent.com/assets/300900/7074735/09742c48-defd-11e4-9d75-559175f6d087.png)

**Comment by jamesrom** [comment]
The wiki is incorrect. 51 is blue. The [first blue flair](http://www.reddit.com/r/thebutton/comments/3167qx/45_master_race/cpzqatg) is 51.

See also [button stats](http://button.cstevens.me/flairs) and [The Catalogue](https://docs.google.com/spreadsheets/d/1v7RV0R9Q133W2QAJSAEqAFrf5v-ACukyQ4py-iWl0jQ/htmlview?sle=true).

**Comment by GLundh** [comment]
Ah. That explains it. Thanks!
